name: Build Android
on:
  workflow_dispatch:
    inputs:
      relese:
        type: string
        required: true
        description: Введите номер релиза (X.X.X)


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm install

      - name: Build Svelte app
        run: npm run build

      - name: Generate boundle static app
        run: npm run generate

      - name: Capacitor update
        run: npx cap add android

      - name: Capacitor copy
        run: npx cap copy

      - name: Set Version android app
        run:  npx capacitor-set-version set:android -v ${{ inputs.relese }}  -b 6 ./

      - name: Build app bundle
        run: cd android && gradle bundle

      - name: Show catalog
        run: ls android/app/build/outputs/bundle/release/

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign dev build
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release(${{ inputs.relese }})
          path: android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60
