name: ci
on:
  push:
    branches:
      - realease/1.0

jobs:
  deploy-admin:
    runs-on: ubuntu-latest

    steps:
      - name: git pull --no-edit
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/arhiterm.by/arhiterm
            git add . && git commit -m "auto commit"
            git pull --no-edit
            ${{ secrets.SCRIPT }}
      - name: install packages
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/arhiterm.by/arhiterm
            npm install --force
      - name: build
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/arhiterm.by/arhiterm
            npm run build && npm run generate
            pm2 restart Arhiterm.by
