name: Build IOS
on:
  workflow_dispatch:
    inputs:
      relese:
        type: string
        required: true
        description: Введите номер релиза (X.X.X)

jobs:
  build:
    name: Build IOS APP
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm install

      - name: Build Svelte app
        run: npm run build

      - name: Generate boundle static app
        run: npm run generate

      - name: Capacitor update
        run: npx cap add ios

      - name: Capacitor copy
        run: npx cap copy

      - name: Set Version IOS app
        run:  npx capacitor-set-version set:ios -v ${{ inputs.relese }}  -b 1 ./

      - name: Install pod
        run: cd ios && pod install

      - name: Build app bundle
        run: xcodebuild build -workspace ios/App/Arhiterm.xcworkspace -scheme ArhitermApp CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Show catalog
        run: ls ios/app/build/outputs/bundle/release/


      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-ios-release(${{ inputs.relese }})
          path: ios/app/build/outputs/bundle/release/*.*
          retention-days: 15
